# Extracted from: LibroAIGateway/cap-12-queue-rag.md
# gateway/app/services/vector_store.py:45-72
class VectorStore(Protocol):
    async def add_vectors(vectors, chunk_ids, payloads) -> list[int | str]: ...
    async def search(query_vector, top_k, threshold, payload_filter) -> list[Hit]: ...
    async def delete_vectors(vector_ids) -> None: ...
    async def delete_collection() -> None: ...
    async def count_active() -> int: ...
