# Source: The FinOps Engineer and the Machine -- Chapter 20
# Pattern: Policy audit trail model

# models/policy_audit.py
class PolicyChangeLog(Base):
    """
    Audit log of FinOps policy changes.
    Automatically generated by the deployment pipeline.
    """
    __tablename__ = "policy_change_log"

    id = Column(Integer, primary_key=True)
    policy_file = Column(String(200), nullable=False)
    changed_by = Column(String(100))
    pr_number = Column(Integer)
    change_summary = Column(Text)
    old_value = Column(JSON)
    new_value = Column(JSON)
    approved_by = Column(String(100))
    deployed_at = Column(DateTime, default=datetime.utcnow)
    environment = Column(String(20))      # staging | production
    rollback_available = Column(Boolean, default=True)
    rollback_commit = Column(String(40))  # hash of the previous commit
