# Source: The DevSecOps and the Machine -- Chapter 18
# Pattern: Runtime security analysis agent with auto-response

# runtime_analyzer/falco_agent.py
"""
Claude agent that analyzes Falco alerts at runtime.
Receives alerts via HTTP webhook, correlates them with the
container inventory, and issues a prioritized verdict.
"""
import anthropic
from fastapi import FastAPI, Request
from pydantic import BaseModel
from datetime import datetime
from typing import Optional

app = FastAPI()
client = anthropic.Anthropic()

# Container inventory and expected behavior
CONTAINER_PROFILES = {
    "inference-service": {
        "expected_processes": ["python3", "gunicorn", "uvicorn"],
        "allowed_outbound": ["api.anthropic.com:443", "qdrant:6333"],
        "allowed_fs_write": ["/tmp", "/var/log"],
        "description": "Inference service with Claude API"
    },
    "agent-worker": {
        "expected_processes": ["python3", "celery"],
        "allowed_outbound": ["api.anthropic.com:443", "redis:6379"],
        "allowed_fs_write": ["/tmp"],
        "description": "Claude agent worker with limited tools"
    },
    "api-gateway": {
        "expected_processes": ["node", "nginx"],
        "allowed_outbound": ["inference-service:8000"],
        "allowed_fs_write": ["/var/log/nginx"],
        "description": "API gateway, no direct LLM access"
    }
}


class FalcoAlert(BaseModel):
    """Structure of a Falco alert."""
    output: str
    priority: str
    rule: str
    time: str
    output_fields: dict
    tags: list[str] = []


def build_analysis_prompt(alert: FalcoAlert) -> str:
    """Build the analysis prompt with environment context."""
    container = alert.output_fields.get("container.name", "unknown")
    profile = CONTAINER_PROFILES.get(container, {})

    return f"""Analyze this Falco security alert and classify it.

## Alert
- Rule: {alert.rule}
- Priority: {alert.priority}
- Time: {alert.time}
- Output: {alert.output}
- Tags: {', '.join(alert.tags)}

## Container context
- Name: {container}
- Expected profile: {profile.get('description', 'Not documented')}
- Allowed processes: {profile.get('expected_processes', 'Not defined')}
- Allowed outbound connections: {profile.get('allowed_outbound', 'Not defined')}
- Allowed writes: {profile.get('allowed_fs_write', 'Not defined')}

## Instructions
1. Classify: TRUE_POSITIVE, FALSE_POSITIVE, or NEEDS_INVESTIGATION
2. Explain in 2-3 sentences why
3. If TRUE_POSITIVE, indicate the real severity (CRITICAL/HIGH/MEDIUM/LOW)
4. If TRUE_POSITIVE, suggest the immediate action
5. If FALSE_POSITIVE, suggest the rule adjustment to prevent future alerts

Respond ONLY in JSON format with the keys:
classification, explanation, real_severity, suggested_action, rule_adjustment"""


@app.post("/webhook/falco")
async def receive_falco_alert(request: Request):
    """Receive Falco alerts and analyze them with Claude."""
    payload = await request.json()
    alert = FalcoAlert(**payload)

    # Only analyze WARNING or higher alerts
    if alert.priority not in ("Warning", "Error", "Critical"):
        return {"status": "skipped", "reason": "low_priority"}

    prompt = build_analysis_prompt(alert)

    # Use claude-haiku-4-5 for fast and cost-effective analysis
    message = client.messages.create(
        model="claude-haiku-4-5",
        max_tokens=512,
        messages=[{"role": "user", "content": prompt}]
    )

    analysis = message.content[0].text

    # Record for auditing and metrics
    log_analysis(alert, analysis)

    # If CRITICAL and TRUE_POSITIVE, escalate immediately
    if (alert.priority == "Critical"
            and '"TRUE_POSITIVE"' in analysis):
        await escalate_to_oncall(alert, analysis)

    return {"status": "analyzed", "analysis": analysis}

# runtime_analyzer/sbom_correlator.py
"""
Correlates Falco alerts with known SBOM vulnerabilities
to enrich the analysis context.
"""
import json
from pathlib import Path


def load_sbom(container_image: str) -> dict:
    """Load the CycloneDX SBOM generated by Syft."""
    sbom_path = Path(f"sboms/{container_image}.cdx.json")
    if not sbom_path.exists():
        return {"components": [], "vulnerabilities": []}
    return json.loads(sbom_path.read_text())


def find_relevant_cves(
    sbom: dict,
    alert_type: str
) -> list[dict]:
    """
    Search for CVEs in the SBOM that are relevant to
    the Falco alert type.

    Mapping of alert types to CVE categories:
    - network → RCE, SSRF, information disclosure
    - filesystem → path traversal, arbitrary file write
    - process → command injection, privilege escalation
    """
    type_to_cwe = {
        "network": ["CWE-918", "CWE-200", "CWE-94"],
        "filesystem": ["CWE-22", "CWE-73"],
        "process": ["CWE-78", "CWE-269"]
    }

    relevant_cwes = type_to_cwe.get(alert_type, [])
    relevant_vulns = []

    for vuln in sbom.get("vulnerabilities", []):
        for cwe in vuln.get("cwes", []):
            if cwe.get("id") in relevant_cwes:
                relevant_vulns.append({
                    "id": vuln.get("id"),
                    "severity": vuln.get("severity"),
                    "component": vuln.get("affects", [{}])[0]
                        .get("ref", "unknown"),
                    "description": vuln.get("description", "")
                })

    return relevant_vulns


def enrich_alert_context(
    container_name: str,
    alert_tags: list[str]
) -> str:
    """Generate additional context for the Claude agent."""
    # Determine alert type from Falco tags
    alert_type = "unknown"
    if "network" in alert_tags or "mitre_exfiltration" in alert_tags:
        alert_type = "network"
    elif "filesystem" in alert_tags or "mitre_persistence" in alert_tags:
        alert_type = "filesystem"
    elif "mitre_execution" in alert_tags:
        alert_type = "process"

    image = get_container_image(container_name)
    sbom = load_sbom(image)
    cves = find_relevant_cves(sbom, alert_type)

    if not cves:
        return "No relevant CVEs found in the SBOM."

    context = "Relevant CVEs in the container SBOM:\n"
    for cve in cves[:5]:  # Limit to the 5 most relevant
        context += (f"- {cve['id']} ({cve['severity']}): "
                   f"{cve['component']} — {cve['description'][:100]}\n")

    return context

# runtime_analyzer/auto_response.py
"""
Automatic containment actions for alerts confirmed
as TRUE_POSITIVE with CRITICAL severity.
Each action is reversible and recorded for auditing.
"""
import subprocess
import logging
from datetime import datetime

logger = logging.getLogger("auto_response")


def isolate_container(container_name: str) -> dict:
    """
    Isolate a compromised container by disconnecting it
    from all networks except the quarantine network.
    Does not destroy the container to allow forensic analysis.
    """
    actions_taken = []

    # Disconnect from the production network
    result = subprocess.run(
        ["docker", "network", "disconnect",
         "production-net", container_name],
        capture_output=True, text=True, timeout=10
    )
    actions_taken.append({
        "action": "network_disconnect",
        "network": "production-net",
        "success": result.returncode == 0,
        "timestamp": datetime.utcnow().isoformat()
    })

    # Connect to the quarantine network (no external access)
    result = subprocess.run(
        ["docker", "network", "connect",
         "quarantine-net", container_name],
        capture_output=True, text=True, timeout=10
    )
    actions_taken.append({
        "action": "network_connect_quarantine",
        "success": result.returncode == 0,
        "timestamp": datetime.utcnow().isoformat()
    })

    logger.critical(
        f"Container {container_name} isolated. "
        f"Actions: {actions_taken}"
    )

    return {
        "container": container_name,
        "status": "isolated",
        "actions": actions_taken,
        "forensics_note": "Container preserved for analysis"
    }