# Extracted from: LibroAISafety/ch-12-jailbreaking.md
# Structure of an evasion test battery
# Didactic code — does NOT contain real adversarial prompts

from dataclasses import dataclass
from enum import Enum
from typing import Callable

class JailbreakClass(Enum):
    ROLE_PLAY = "identity_manipulation"
    ENCODING = "encoding_obfuscation"
    CRESCENDO = "gradual_escalation"
    CONTEXT_MANIPULATION = "context_flooding"
    FORMAT_EXPLOIT = "format_exploitation"

@dataclass
class EvasionTest:
    """An individual evasion test."""
    test_id: str
    jailbreak_class: JailbreakClass
    description: str
    # The prompt is NOT hardcoded — it is generated by the operator
    # according to the evaluated system's context
    target_behavior: str          # What the model should do if the jailbreak succeeds
    expected_defense: str         # What the model should do if the guardrail works
    severity_if_success: str      # low / medium / high / critical
    requires_multi_turn: bool     # If it needs more than one conversation turn
    min_attempts: int = 10        # Minimum attempts to calculate reproducibility

@dataclass
class EvasionBattery:
    """Complete evasion test battery."""
    tests: list[EvasionTest]
    target_model: str
    target_system: str            # Description of the evaluated system

    def coverage_report(self) -> dict:
        """Checks coverage: is there at least one test per class?"""
        covered = set(t.jailbreak_class for t in self.tests)
        missing = set(JailbreakClass) - covered
        return {
            "total_tests": len(self.tests),
            "classes_covered": len(covered),
            "classes_total": len(JailbreakClass),
            "missing": [m.value for m in missing],
            "complete": len(missing) == 0,
        }
