# Source: The DevSecOps and the Machine -- Chapter 3
# Pattern: STRIDE threat modeling agent with Claude

"""
stride_classifier.py — Claude agent that applies STRIDE
to each asset in the inventory and generates a threat model
prioritized by severity and exposure.
"""
import anthropic
import json

STRIDE_CATEGORIES = [
    "Spoofing", "Tampering", "Repudiation",
    "Information Disclosure", "Denial of Service",
    "Elevation of Privilege"
]

SYSTEM_PROMPT = """You are a security analyst specializing in STRIDE threat
modeling for systems with AI. You receive an asset from the pipeline
inventory and must evaluate each STRIDE category.

For each category, respond with:
- applicable: true/false — is this threat relevant for this asset?
- severity: critical/high/medium/low — if applicable
- threat: concise description of the specific threat (1-2 sentences)
- mitigation: recommended technical control (1-2 sentences)

Respond ONLY with valid JSON. Do not add explanations outside the JSON.
If the asset is of type llm_endpoint, rag_corpus, or agent_tool,
pay special attention to AI-specific threats:
prompt injection, data poisoning, excessive agency.

Response format:
{
  "asset": "<asset name>",
  "threats": [
    {
      "stride_category": "<category>",
      "applicable": true,
      "severity": "high",
      "threat": "...",
      "mitigation": "..."
    }
  ]
}"""

def classify_asset_threats(
    client: anthropic.Anthropic,
    asset: dict
) -> dict:
    """Send an asset to the Claude agent for STRIDE classification."""
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2048,
        system=SYSTEM_PROMPT,
        messages=[{
            "role": "user",
            "content": (
                f"Analyze this pipeline inventory asset:\n"
                f"```json\n{json.dumps(asset, indent=2)}\n```\n\n"
                f"Evaluate all 6 STRIDE categories."
            )
        }]
    )
    return json.loads(message.content[0].text)

def run_stride_analysis(inventory: list[dict]) -> list[dict]:
    """Run STRIDE analysis for the entire inventory."""
    client = anthropic.Anthropic(api_key="<YOUR_API_KEY>")
    results = []
    for asset in inventory:
        analysis = classify_asset_threats(client, asset)
        # Filter only applicable threats
        applicable = [
            t for t in analysis.get("threats", [])
            if t.get("applicable", False)
        ]
        results.append({
            "asset": asset["name"],
            "category": asset["category"],
            "exposed": asset.get("exposed", False),
            "threat_count": len(applicable),
            "critical_count": sum(
                1 for t in applicable if t["severity"] == "critical"
            ),
            "threats": applicable
        })
    # Sort by severity: those with critical threats first
    results.sort(
        key=lambda r: (-r["critical_count"], -r["threat_count"])
    )
    return results

if __name__ == "__main__":
    # Load inventory generated by pipeline_inventory.py
    with open("inventory.json") as f:
        inventory = json.load(f)
    analysis = run_stride_analysis(inventory)
    with open("threat_model.json", "w") as f:
        json.dump(analysis, f, indent=2, ensure_ascii=False)
    # Executive summary
    total_threats = sum(r["threat_count"] for r in analysis)
    critical = sum(r["critical_count"] for r in analysis)
    print(f"Assets analyzed: {len(analysis)}")
    print(f"Threats identified: {total_threats}")
    print(f"Critical threats: {critical}")